// apps/web/src/pages/docs/frameworks/astro/Theming.tsx
import SyntaxBlock from '@/components/docs/SyntaxBlock';

interface Props {
  copiedField: string | null;
  onCopy: (text: string, field: string) => void;
}

export default function Theming({ copiedField, onCopy }: Props) {
  return (
    <>
      <h3 className="text-lg font-sans font-medium text-text-base mb-4 mt-10">Styling &amp; Tailwind CSS</h3>
      <p className="text-text-base/60 text-[15px] leading-[1.8] mb-4">
        Icons inherit their parent's text color by default via <code className="text-text-base/70 bg-text-base/6 px-1.5 py-0.5 rounded text-[12px]">currentColor</code>. You can easily style icons using Tailwind CSS utility classes or custom inline CSS.
      </p>

      <SyntaxBlock
        title="Tailwind CSS Example"
        onCopy={() => onCopy(`---\nimport { Home, ShieldCheck, Heart } from 'reicon-astro';\n---\n\n<div class="flex items-center gap-4 text-gray-700 dark:text-gray-200">\n  <Home class="w-6 h-6 hover:text-indigo-500 transition-colors" />\n  <ShieldCheck class="w-6 h-6 text-green-500" />\n  <Heart class="w-6 h-6 text-rose-500 fill-current" />\n</div>`, 'astro-theming')}
        copied={copiedField === 'astro-theming'}
      >
        <span className="text-text-base/30">---</span>
        {'\n'}
        <span className="text-[#c678dd]">import</span>
        <span className="text-text-base/70">{' { '}</span>
        <span className="text-[#e5c07b]">Home</span>
        <span className="text-text-base/70">, </span>
        <span className="text-[#e5c07b]">ShieldCheck</span>
        <span className="text-text-base/70">, </span>
        <span className="text-[#e5c07b]">Heart</span>
        <span className="text-text-base/70">{' } '}</span>
        <span className="text-[#c678dd]">from</span>
        <span className="text-[#98c379]"> 'reicon-astro'</span>
        <span className="text-text-base/30">;</span>
        {'\n'}
        <span className="text-text-base/30">---</span>
        {'\n\n'}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">div</span><span className="text-[#d19a66]"> class</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"flex items-center gap-4 text-gray-700 dark:text-gray-200"</span><span className="text-text-base/70">{'>'}</span>
        {'\n  '}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">Home</span><span className="text-[#d19a66]"> class</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"w-6 h-6 hover:text-indigo-500 transition-colors"</span><span className="text-text-base/70"> /{'>'}</span>
        {'\n  '}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">ShieldCheck</span><span className="text-[#d19a66]"> class</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"w-6 h-6 text-green-500"</span><span className="text-text-base/70"> /{'>'}</span>
        {'\n  '}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">Heart</span><span className="text-[#d19a66]"> class</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"w-6 h-6 text-rose-500 fill-current"</span><span className="text-text-base/70"> /{'>'}</span>
        {'\n'}
        <span className="text-text-base/70">{'</'}</span><span className="text-[#e06c75]">div</span><span className="text-text-base/70">{'>'}</span>
      </SyntaxBlock>
    </>
  );
}

// apps/web/src/pages/docs/frameworks/vue/Theming.tsx
import SyntaxBlock from '@/components/docs/SyntaxBlock';

interface Props {
  copiedField: string | null;
  onCopy: (text: string, field: string) => void;
}

export default function Theming({ copiedField, onCopy }: Props) {
  return (
    <>
      {/* Dynamic Icons */}
      <h3 className="text-lg font-sans font-medium text-text-base mb-4 mt-10">Dynamic Icons</h3>
      <p className="text-text-base/60 text-[15px] leading-[1.8] mb-4">
        Use Vue's <code className="text-text-base/70 bg-text-base/6 px-1.5 py-0.5 rounded text-[12px]">{'<component :is="..." />'}</code> pattern with <code className="text-text-base/70 bg-text-base/6 px-1.5 py-0.5 rounded text-[12px]">shallowRef</code> for dynamic icon switching.
      </p>

      <SyntaxBlock
        title="Dynamic"
        onCopy={() => onCopy("<script setup>\nimport { Home, Settings, User } from 'reicon-vue';\nimport { shallowRef } from 'vue';\n\nconst currentIcon = shallowRef(Home);\n</script>\n\n<template>\n  <component :is=\"currentIcon\" :size=\"32\" />\n</template>", 'vue-dynamic')}
        copied={copiedField === 'vue-dynamic'}
      >
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">script setup</span><span className="text-text-base/70">{'>'}</span>
        {'\n'}
        <span className="text-[#c678dd]">import</span>
        <span className="text-text-base/70">{' { '}</span>
        <span className="text-[#e5c07b]">Home</span><span className="text-text-base/70">, </span>
        <span className="text-[#e5c07b]">Settings</span><span className="text-text-base/70">, </span>
        <span className="text-[#e5c07b]">User</span>
        <span className="text-text-base/70">{' } '}</span>
        <span className="text-[#c678dd]">from</span>
        <span className="text-[#98c379]"> 'reicon-vue'</span><span className="text-text-base/30">;</span>
        {'\n'}
        <span className="text-[#c678dd]">import</span>
        <span className="text-text-base/70">{' { '}</span>
        <span className="text-[#e5c07b]">shallowRef</span>
        <span className="text-text-base/70">{' } '}</span>
        <span className="text-[#c678dd]">from</span>
        <span className="text-[#98c379]"> 'vue'</span><span className="text-text-base/30">;</span>
        {'\n\n'}
        <span className="text-[#c678dd]">const</span><span className="text-[#e5c07b]"> currentIcon</span><span className="text-text-base/70"> = </span><span className="text-[#61afef]">shallowRef</span><span className="text-text-base/70">(Home);</span>
        {'\n'}
        <span className="text-text-base/70">{'</'}</span><span className="text-[#e06c75]">script</span><span className="text-text-base/70">{'>'}</span>
        {'\n\n'}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">template</span><span className="text-text-base/70">{'>'}</span>
        {'\n  '}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">component</span><span className="text-[#d19a66]"> :is</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"currentIcon"</span><span className="text-[#d19a66]"> :size</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"32"</span><span className="text-text-base/70"> /{'>'}</span>
        {'\n'}
        <span className="text-text-base/70">{'</'}</span><span className="text-[#e06c75]">template</span><span className="text-text-base/70">{'>'}</span>
      </SyntaxBlock>

      {/* Nuxt 3 */}
      <h3 className="text-lg font-sans font-medium text-text-base mb-4 mt-10">Nuxt 3</h3>
      <p className="text-text-base/60 text-[15px] leading-[1.8] mb-4">
        Works out of the box with Nuxt 3 - just import and use. No plugins or configuration needed.
      </p>

      <SyntaxBlock
        title="Nuxt 3"
        onCopy={() => onCopy("<script setup>\nimport { Home } from 'reicon-vue';\n</script>\n\n<template>\n  <Home :size=\"24\" />\n</template>", 'vue-nuxt')}
        copied={copiedField === 'vue-nuxt'}
      >
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">script setup</span><span className="text-text-base/70">{'>'}</span>
        {'\n'}
        <span className="text-[#c678dd]">import</span>
        <span className="text-text-base/70">{' { '}</span>
        <span className="text-[#e5c07b]">Home</span>
        <span className="text-text-base/70">{' } '}</span>
        <span className="text-[#c678dd]">from</span>
        <span className="text-[#98c379]"> 'reicon-vue'</span><span className="text-text-base/30">;</span>
        {'\n'}
        <span className="text-text-base/70">{'</'}</span><span className="text-[#e06c75]">script</span><span className="text-text-base/70">{'>'}</span>
        {'\n\n'}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">template</span><span className="text-text-base/70">{'>'}</span>
        {'\n  '}
        <span className="text-text-base/70">{'<'}</span><span className="text-[#e06c75]">Home</span><span className="text-[#d19a66]"> :size</span><span className="text-text-base/50">=</span><span className="text-[#98c379]">"24"</span><span className="text-text-base/70"> /{'>'}</span>
        {'\n'}
        <span className="text-text-base/70">{'</'}</span><span className="text-[#e06c75]">template</span><span className="text-text-base/70">{'>'}</span>
      </SyntaxBlock>

      <div className="mt-6 bg-[#4DBA87]/6 rounded-xl p-4 text-[13px] text-text-base/60 leading-relaxed border-0">
        <span className="text-[#4DBA87] font-semibold">Note:</span> All icon components are SSR-compatible and work with Nuxt 3, Vite, and other Vue 3 frameworks out of the box.
      </div>
    </>
  );
}
